In [1]:
import numpy as np
from numpy.linalg import norm
from random import normalvariate
from math import sqrt

In [2]:
def randomUnitVector(n):
    unnormalized = [normalvariate(0, 1) for _ in range(n)]
    theNorm = sqrt(sum(x * x for x in unnormalized))
    return [x / theNorm for x in unnormalized]

In [3]:
def svd_1d(A, epsilon=1e-10):
    ''' The one-dimensional SVD '''

    n, m = A.shape
    x = randomUnitVector(m)
    lastV = None
    currentV = x

    if n > m:
        B = np.dot(A.T, A)
    else:
        B = np.dot(A, A.T)

    iterations = 0
    while True:
        iterations += 1
        lastV = currentV
        currentV = np.dot(B, lastV)
        currentV = currentV / norm(currentV)

        if abs(np.dot(currentV, lastV)) > 1 - epsilon:
            print("converged in {} iterations!".format(iterations))
            return currentV

In [4]:
def svd(A, k=None, epsilon=1e-10):
    '''
        Compute the singular value decomposition of a matrix A
        using the power method. A is the input matrix, and k
        is the number of singular values you wish to compute.
        If k is None, this computes the full-rank decomposition.
    '''
    n, m = A.shape
    svdSoFar = []
    if k is None:
        k = min(n, m)

    for i in range(k):
        matrixFor1D = A.copy()

        for singularValue, u, v in svdSoFar[:i]:
            matrixFor1D -= singularValue * np.outer(u, v)

        v = svd_1d(matrixFor1D, epsilon=epsilon)  # next singular vector
        u_unnormalized = np.dot(A, v)
        sigma = norm(u_unnormalized)  # next singular value
        u = u_unnormalized / sigma

        svdSoFar.append((sigma, u, v))

    singularValues, us, vs = [np.array(x) for x in zip(*svdSoFar)]
    return singularValues, us.T, vs


if __name__ == "__main__":
    movieRatings = np.array([
        [2, 5, 3],
        [1, 2, 1],
        [4, 1, 1],
        [3, 5, 2],
        [5, 3, 1],
        [4, 5, 5],
        [2, 4, 2],
        [2, 2, 5],
    ], dtype='float64')

    # v1 = svd_1d(movieRatings)
    # print(v1)

    theSVD = svd(movieRatings)

converged in 5 iterations!
converged in 25 iterations!
converged in 2 iterations!


In [5]:
theSVD

(array([ 15.09626916,   4.30056855,   3.40701739]),
 array([[ 0.3945853 ,  0.23924109,  0.35445268],
        [ 0.15830233,  0.03055146,  0.15299676],
        [ 0.22155194, -0.52086818, -0.39333521],
        [ 0.39692634, -0.08648381,  0.41053113],
        [ 0.34630248, -0.64129003, -0.07381141],
        [ 0.53347452,  0.19168454, -0.19949858],
        [ 0.31660465,  0.06110291,  0.30599352],
        [ 0.32840229,  0.45969312, -0.62355998]]),
 array([[ 0.54184774,  0.67071001,  0.50650678],
        [-0.75153119,  0.11682437,  0.64927108],
        [-0.37630027,  0.73246171, -0.56736051]]))